"""Report writers: JSON (machine) and Markdown (human) - milestone M5.

Both consume the dict produced by
:func:`nesting.analysis.compare.build_report`; the JSON shape is specified
in ``docs/report-schema.md``.
"""

from __future__ import annotations

import json
from pathlib import Path


def write_json_report(report: dict, path: str | Path) -> Path:
    """Write the comparison report as JSON."""
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(report, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    return path


def write_markdown_report(report: dict, path: str | Path) -> Path:
    """Write the comparison report as Markdown."""
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    lines: list[str] = []

    lines.append("# Nesting comparison report")
    lines.append("")
    generated_by = report.get("generated_by", "?")
    lines.append(f"Generated by {generated_by} - schema v{report.get('schema_version', 1)}")
    lines.append("")

    job = report.get("job", {})
    lines.append("## Job")
    lines.append("")
    lines.append("| Field | Value |")
    lines.append("|---|---|")
    lines.append(f"| Source file | `{job.get('source_file', '?')}` |")
    lines.append(f"| DXF version | {job.get('dxf_version', '?')} |")
    lines.append(f"| Unit | {job.get('unit', '?')} |")
    sheet = job.get("sheet", {})
    lines.append(f"| Sheet | {sheet.get('width', '?')} x {sheet.get('height', '?')} mm |")
    parts = job.get("parts", {})
    lines.append(
        f"| Parts | {parts.get('unique', '?')} unique / {parts.get('total_quantity', '?')} total"
        f" ({parts.get('total_area_mm2', 0):,.0f} mm2) |"
    )
    lines.append("")

    names = sorted(report.get("strategies", {}))
    if not names:
        lines.append("_No strategies were run._")
        path.write_text("\n".join(lines) + "\n", encoding="utf-8")
        return path

    lines.append("## Metric comparison")
    lines.append("")
    header = "| Metric | " + " | ".join(names) + " | Better |"
    lines.append(header)
    lines.append("|" + "---|" * (len(names) + 2))
    for row in report["comparison"]["table"]:
        cells = " | ".join(str(row[name]) for name in names)
        better = row.get("better")
        better_cell = f"**{better}**" if better else "tie"
        lines.append(f"| {row['metric']} | {cells} | {better_cell} |")
    lines.append("")

    for name in names:
        strategy = report["strategies"][name]
        metrics = strategy["metrics"]
        lines.append(f"## {name}")
        lines.append("")
        lines.append(
            f"- Sheets: **{metrics['sheet_count']}** "
            f"({metrics['unique_sheet_layouts']} unique layout(s), "
            f"copies per layout: {metrics['copy_counts']})"
        )
        lines.append(
            f"- Utilization: **{metrics['utilization_pct']}%** net / "
            f"{metrics['utilization_gross_pct']}% gross of kerf"
        )
        lines.append(f"- Replication efficiency: **{metrics['replication_efficiency']}**")
        lines.append(
            f"- Cut length {metrics['total_cut_length_mm']:,.0f} mm - "
            f"{metrics['pierce_count']} pierces - "
            f"rapid travel {metrics['rapid_travel_mm']:,.0f} mm"
        )
        if strategy["unplaced"]:
            unplaced = ", ".join(f"{u['part_id']} x{u['quantity']}" for u in strategy["unplaced"])
            lines.append(f"- **Unplaced parts: {unplaced}**")
        lines.append("")

    recommendation = report["comparison"].get("recommendation")
    if recommendation:
        lines.append("## Recommendation")
        lines.append("")
        lines.append(
            f"**{recommendation['strategy']}** is the more effective approach for this job."
        )
        lines.append("")
        scores = " vs ".join(f"{name}: {score}" for name, score in recommendation["scores"].items())
        weights = recommendation.get("weights", {})
        lines.append(f"Weighted score ({scores}; weights: {weights}):")
        lines.append("")
        for note in recommendation["rationale"]:
            lines.append(f"- {note}")
        lines.append("")

    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path
